/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed-variant": "#5c4300",
        "surface-container-lowest": "#ffffff",
        "background": "#f7f9fb",
        "on-tertiary-container": "#fffbff",
        "primary-fixed": "#d8e2ff",
        "surface-container-highest": "#e0e3e5",
        "on-primary-container": "#fefcff",
        "outline-variant": "#c2c6d6",
        "tertiary": "#994100",
        "secondary-fixed": "#ffdf9f",
        "on-primary-fixed-variant": "#004395",
        "on-surface-variant": "#424754",
        "error-container": "#ffdad6",
        "outline": "#727785",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "primary-container": "#2170e4",
        "surface-tint": "#005ac2",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-secondary-fixed": "#261a00",
        "on-error": "#ffffff",
        "secondary": "#795900",
        "surface-container-low": "#f2f4f6",
        "inverse-surface": "#2d3133",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb690",
        "primary": "#0058be",
        "on-tertiary-fixed-variant": "#783200",
        "surface-dim": "#d8dadc",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary-container": "#6f5100",
        "tertiary-container": "#c05400",
        "on-tertiary-fixed": "#341100",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef0",
        "on-error-container": "#93000a",
        "inverse-primary": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "secondary-fixed-dim": "#f9bd22",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed": "#ffdbca",
        "secondary-container": "#ffc329",
        "surface-bright": "#f7f9fb",
        "surface": "#f7f9fb"
      },
      spacing: {
        "unit": "8px",
        "section-padding": "48px",
        "card-gap": "20px",
        "container-margin": "24px"
      },
      fontFamily: {
        "pro-body": ["Inter", "sans-serif"],
        "stat-label": ["Inter", "sans-serif"],
        "student-h1": ["Lexend", "sans-serif"],
        "pro-h1": ["Inter", "sans-serif"],
        "student-body": ["Lexend", "sans-serif"],
        "lexend": ["Lexend", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
      fontSize: {
        "pro-body": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "stat-label": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "student-h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "pro-h1": ["28px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "student-body": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }]
      },
      keyframes: {
        typewriter: {
          "0%": { width: "0ch" },
          "100%": { width: "100%" },
        },
        blinkCaret: {
          "0%, 100%": { borderColor: "transparent" },
          "50%": { borderColor: "currentColor" },
        },
        progress: {
          "0%": { width: "0%" },
          "50%": { width: "100%" },
          "100%": { width: "0%" },
        },
        wave: {
          "0%": { transform: "scale(1)", opacity: "0.8" },
          "100%": { transform: "scale(2.5)", opacity: "0" },
        },
      },
      animation: {
        typewriter: "typewriter 3s steps(30) forwards",
        blinkCaret: "blinkCaret 0.75s step-end infinite",
        progress: "progress 2s ease-in-out infinite",
        wave: "wave 1.5s ease-out infinite",
      },
    },
  },
  plugins: [],
};
