const fs = require('fs');
const path = require('path');

const sites = ['Pit0002', 'Aja0003'];

sites.forEach(siteId => {
  const filePath = path.join(__dirname, '..', 'dataset', siteId, 'image', 'annotations.json');
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    const initialCount = data.length;
    // Filter out corrupted records generated by the last run
    const cleaned = data.filter(q => q.question_type === 'IMAGE_MCQ');
    if (cleaned.length < initialCount) {
      console.log(`[${siteId}] Removed ${initialCount - cleaned.length} corrupted annotations.`);
      fs.writeFileSync(filePath, JSON.stringify(cleaned, null, 2));
    } else {
      console.log(`[${siteId}] No corrupted annotations found.`);
    }
  }
});
